name: to_be
description: A discipline and productivity app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  flutter_local_notifications: ^19.5.0
  firebase_database: ^12.1.0 
  in_app_purchase: ^3.1.11
  device_apps: ^2.2.0
  http: ^1.1.2
  confetti: ^0.8.0
  fl_chart: ^1.1.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  permission_handler: ^12.0.1
  cloudflare_turnstile: ^3.6.2
  uuid: ^4.0.0
  device_preview: ^1.3.1
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^7.2.0
  google_sign_in_ios: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/